#!/usr/bin/env python3
"""Roll up docs/*_plan.md into docs/_tracks_index.json — one row per track.

Reality check before you trust this script's output: only planetary_health_plan.md
actually uses the "### Cycle N — DATE" convention this was first specced against.
The other 11 plans use varied heading styles (a dated H1 title, dated H2 sections,
"NEXT ACTION (APPROVED date)"). So this extracts the LAST dated heading of any
form, plus any explicit status marker (PAUSED/PARKED/DEFERRED/HALTED/SHIPPED/
MERGED/COMPLETE/APPROVED).

The living-plan convention (its own docstring) keeps CURRENT status in a boot
header at the TOP and an append-only history in a "Cycle log" at the FOOT. The
header is authoritative for "is this track live"; the foot is history and
routinely mentions a past SUB-COMPONENT being parked without the track itself
being parked — planetary_health_plan.md's own foot says "airflow parked" about
a data source, three lines from the file's end, while its boot header shows an
actively-worked track. So the header is searched first; the tail is a lower-
confidence fallback, labelled as such.

Consumed by ~/SCL/SCR/scripts/build_tracks.py (the workspace-level TRACKS.json
rollup). Regenerate after any docs/*_plan.md edit; never hand-edit the output.
"""
import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "_tracks_index.json"

DATE_RE = re.compile(r"2026-\d{2}-\d{2}")
HEADING_RE = re.compile(r"^#{1,4}\s+.*$", re.M)
CYCLE_LOG_RE = re.compile(r"^#{1,3}\s*Cycle log\b|^#{2,4}\s*Cycle\s+\d+\s*[—-]", re.I | re.M)
# Marker + the sentence carrying it, so a human can tell "the TRACK is parked"
# from "one sub-component the track depends on is parked" at a glance.
MARKER_RE = re.compile(
    r"[^.\n]*\b(PAUSED|PARKED|DEFERRED|HALTED|SHIPPED|MERGED|COMPLETE|APPROVED)\b[^.\n]*",
    re.I,
)
STALE_DAYS = 14


def latest_dated_heading(text: str):
    dated = [h for h in HEADING_RE.findall(text) if DATE_RE.search(h)]
    if not dated:
        return None, None
    h = dated[-1]
    date = DATE_RE.search(h).group(0)
    return h.strip("# ").strip(), date


def find_marker(text: str, heading: str):
    log_start = CYCLE_LOG_RE.search(text)
    header = text[: log_start.start()] if log_start else text[:2000]
    m = MARKER_RE.search(heading or "") or MARKER_RE.search(header)
    if m:
        return m.group(0).strip(), "header"
    m = MARKER_RE.search(text[-1500:])
    if m:
        return m.group(0).strip(), "tail (lower confidence — may describe a sub-component, not the track)"
    return None, None


def main():
    tracks = []
    for f in sorted((ROOT / "docs").glob("*_plan.md")):
        text = f.read_text(encoding="utf-8", errors="replace")
        heading, date = latest_dated_heading(text)
        sentence, scope = find_marker(text, heading)
        marker = None
        if sentence:
            marker = re.search(
                r"PAUSED|PARKED|DEFERRED|HALTED|SHIPPED|MERGED|COMPLETE|APPROVED", sentence, re.I
            ).group(0).upper()
        mtime = datetime.fromtimestamp(f.stat().st_mtime, tz=timezone.utc)
        # file mtime, not the extracted heading date, is "last_touched": several
        # plans list Cycle entries newest-first within the foot section, so "the
        # last dated heading in document order" can be the OLDEST cycle, not the
        # newest (caught on planetary_health_plan.md: heading said 2026-07-05,
        # actual last edit was 2026-08-18). The heading is kept as context only.
        last_touched = mtime.date().isoformat()
        stale_days = (datetime.now(timezone.utc) - mtime).days
        tracks.append({
            "track": f.stem.replace("_plan", ""),
            "file": str(f.relative_to(ROOT)),
            "last_heading": heading,
            "last_touched": last_touched,
            "file_mtime": mtime.date().isoformat(),
            "stale_days": stale_days,
            "status": marker.lower() if marker else "unclear (no explicit marker found)",
            "status_evidence": sentence,
            "status_scope": scope,
            "flag": "STALE" if stale_days > STALE_DAYS and not marker else None,
        })

    OUT.write_text(json.dumps({
        "_doc": "Generated by scripts/build_tracks_index.py — do not hand-edit.",
        "generated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "stale_threshold_days": STALE_DAYS,
        "tracks": tracks,
    }, indent=2, ensure_ascii=False) + "\n")

    n_stale = sum(1 for t in tracks if t["flag"] == "STALE")
    n_unclear = sum(1 for t in tracks if "unclear" in t["status"])
    print(f"wrote {OUT} — {len(tracks)} tracks, {n_stale} stale, {n_unclear} unmarked")


if __name__ == "__main__":
    main()
