"""Phase 3: migrate the campaign indicator files to rectangular-domain v1 schema.

Augments two CSVs per site with the new audit columns and drops the
deprecated cylindrical-domain column ``blocken_radius_required``:

1. **campaign_patches.csv** (canonical, 119 rows total) — read by
   ``analyze_cfd_results.py`` as the source of truth for centers +
   covariates. All 119 patches get the new columns.
2. **per_patch_indicators.csv** (downstream, currently 110 of the 119
   campaign rows) — generated by the analysis pipeline when CFD
   results land. Only the rows it currently carries are updated; the
   missing 9 (CDA / Maré / Rocinha went 22 → 25 after the synthetic
   CFD pass) get the new columns the next time
   ``analyze_cfd_results.py`` rebuilds the file from campaign_patches.

Both files are dropped of ``blocken_radius_required`` (cylindrical
artifact, no downstream consumers in src/cfd_integration/ or
analyze_cfd_results.py).

Idempotent: re-running on an already-migrated CSV refreshes the new
columns from audit_v1.csv without duplicating them.

Run::

    python scripts/migrate_indicators_rectangular_v1.py            # dry-run
    python scripts/migrate_indicators_rectangular_v1.py --apply    # write
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SITES = ["vidigal", "riodaspedras", "rocinha", "complexo_do_alemao", "maré"]
AUDIT_CSV = PROJECT_ROOT / "outputs" / "comparative" / "cfd_methodology" / "audit_v1.csv"

# Cylindrical-domain artifact to drop. blocken_ok and cfd_domain_radius
# are listed in the original migration prompt but never actually exist in
# the indicator files — left out of DEPRECATED to avoid noisy warnings.
DEPRECATED = ["blocken_radius_required"]

WIND_DIRS = ["N", "NE", "E", "SE", "S", "SW", "W", "NW"]
NEW_COLUMNS = [
    "lambda_p_patch",
    *[f"lambda_f_{d}" for d in WIND_DIRS],
    "lambda_f_mean",
    "lambda_f_max",
    "lambda_f_max_dir",
    "H_mean",  # already in source, but rewritten consistently from audit
    "domain_upstream_m",
    "domain_downstream_m",
    "domain_lateral_m",
    "domain_top_m",
    "domain_blockage_frontal_m2",
    "domain_blockage_cross_section_m2",
    "domain_blockage_ratio",
    "domain_blockage_ok",
    "lambda_f_blockage_diag",
    "source_data_required_m",
    "source_data_extent_m",
    "source_data_ok",
    "eligible",
]


def _migrate_file(path: Path, audit: pd.DataFrame, site: str, apply: bool) -> tuple[int, int, str]:
    if not path.exists():
        return 0, 0, f"  [SKIP] {site}: file missing at {path}"

    df = pd.read_csv(path)
    n_before = len(df.columns)

    drop_cols = [c for c in DEPRECATED if c in df.columns]
    if drop_cols:
        df = df.drop(columns=drop_cols)

    site_audit = audit[audit["site"] == site].copy()
    if site_audit.empty:
        return 0, 0, f"  [WARN] {site}: no rows in audit_v1.csv — skipping {path.name}"

    # Drop any existing NEW_COLUMNS so the merge is idempotent.
    present_new = [c for c in NEW_COLUMNS if c in df.columns]
    if present_new:
        df = df.drop(columns=present_new)

    audit_cols = ["patch_id"] + [c for c in NEW_COLUMNS if c in site_audit.columns]
    df = df.merge(site_audit[audit_cols], on="patch_id", how="left")

    n_after = len(df.columns)
    n_added = n_after - n_before + len(drop_cols)
    n_eligible = int(df["eligible"].sum()) if "eligible" in df.columns else 0

    msg = (
        f"  {path.name:30s}  rows={len(df):3d}  cols {n_before}→{n_after}  "
        f"+{n_added} new, -{len(drop_cols)} deprecated  eligible={n_eligible}/{len(df)}"
    )

    if apply:
        df.to_csv(path, index=False)
    return n_added, n_eligible, msg


def _migrate_one(audit: pd.DataFrame, site: str, apply: bool) -> tuple[int, int]:
    canon = PROJECT_ROOT / "outputs" / site / "sampling_cfd" / "campaign_sampling" / "campaign_patches.csv"
    derived = PROJECT_ROOT / "outputs" / site / "cfd_analysis" / "per_patch_indicators.csv"

    print(f"  {site}:")
    n1, e1, m1 = _migrate_file(canon, audit, site, apply)
    print(m1)
    _, _, m2 = _migrate_file(derived, audit, site, apply)
    print(m2)
    return n1, e1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Write the migrated CSV in place. Without this flag the script is a dry-run.",
    )
    args = parser.parse_args()

    if not AUDIT_CSV.exists():
        print(f"ERROR: audit file missing at {AUDIT_CSV}", file=sys.stderr)
        print("Run scripts/audit_rectangular_domain.py first.", file=sys.stderr)
        return 1

    audit = pd.read_csv(AUDIT_CSV)
    expected_cols = {"site", "patch_id", *NEW_COLUMNS}
    missing = expected_cols - set(audit.columns)
    if missing:
        print(f"ERROR: audit file is missing columns: {sorted(missing)}", file=sys.stderr)
        return 1

    print(f"  audit:  {AUDIT_CSV.relative_to(PROJECT_ROOT)}")
    print(f"  rows:   {len(audit)}")
    print(f"  mode:   {'APPLY (writing)' if args.apply else 'DRY-RUN'}")
    print()

    total_added, total_eligible = 0, 0
    for site in SITES:
        added, elig = _migrate_one(audit, site, apply=args.apply)
        total_added += added
        total_eligible += elig

    print()
    print(f"  total eligible: {total_eligible}/{len(audit)}")
    if not args.apply:
        print()
        print("  DRY-RUN — no files written. Re-run with --apply to commit.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
